server:
  port: 8080

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: carros
          uri: http://localhost:8082
          predicates:
            - Path=/api/carro/**
        - id: motos
          uri: http://localhost:8083
          predicates:
            - Path=/api/moto/**
        - id: users
          uri: http://localhost:8081
          predicates:
            - Path=/api/usuario/**