#Para trabajar con el config-server
spring:
  application:
    name: microservice-gateway
  config:
    import: optional:configserver:http://localhost:8888

##Para trabajar sin el config-server
#server:
#  port: 8080
#
#spring:
#  application:
#    name: microservice-gateway
#  config:
#    import: optional:configserver:http://localhost:8888
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: carros
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/carro/**
#        - id: motos
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/moto/**
#        - id: usuarios
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/usuario/**